const AWS_BASE = 'https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/main/dist';
const SIMPLE_BASE = 'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons';

const AWS_MAP: Record<string, string> = {
  'EC2': `${AWS_BASE}/Compute/EC2.png`,
  'EC2 Instance': `${AWS_BASE}/Compute/EC2.png`,
  'Lambda': `${AWS_BASE}/Compute/Lambda.png`,
  'Lambda Function': `${AWS_BASE}/Compute/Lambda.png`,
  'ECS': `${AWS_BASE}/Containers/ElasticContainerService.png`,
  'ECS Container': `${AWS_BASE}/Containers/ElasticContainerService.png`,
  'EKS': `${AWS_BASE}/Containers/ElasticKubernetesService.png`,
  'EKS Cluster': `${AWS_BASE}/Containers/ElasticKubernetesService.png`,
  'Fargate': `${AWS_BASE}/Containers/Fargate.png`,
  'Batch': `${AWS_BASE}/Compute/Batch.png`,
  'Batch Job': `${AWS_BASE}/Compute/Batch.png`,
  
  'S3': `${AWS_BASE}/Storage/SimpleStorageService.png`,
  'S3 Bucket': `${AWS_BASE}/Storage/SimpleStorageService.png`,
  'EBS': `${AWS_BASE}/Storage/ElasticBlockStore.png`,
  'EBS Volume': `${AWS_BASE}/Storage/ElasticBlockStore.png`,
  'Glacier': `${AWS_BASE}/Storage/SimpleStorageService.png`,
  'S3 Glacier': `${AWS_BASE}/Storage/SimpleStorageService.png`,
  
  'VPC': `${AWS_BASE}/Groups/VPC.png`,
  'VPC Network': `${AWS_BASE}/Groups/VPC.png`,
  'ALB': `${AWS_BASE}/NetworkingContentDelivery/ElasticLoadBalancing.png`,
  'Load Balancer (ALB)': `${AWS_BASE}/NetworkingContentDelivery/ElasticLoadBalancing.png`,
  'CloudFront': `${AWS_BASE}/NetworkingContentDelivery/CloudFront.png`,
  'CloudFront CDN': `${AWS_BASE}/NetworkingContentDelivery/CloudFront.png`,
  'Route53': `${AWS_BASE}/NetworkingContentDelivery/Route53.png`,
  'Route53 DNS': `${AWS_BASE}/NetworkingContentDelivery/Route53.png`,
  'API Gateway': `${AWS_BASE}/NetworkingContentDelivery/APIGateway.png`,
  
  'RDS': `${AWS_BASE}/Database/RDS.png`,
  'RDS Database': `${AWS_BASE}/Database/RDS.png`,
  'DynamoDB': `${AWS_BASE}/Database/DynamoDB.png`,
  'ElastiCache': `${AWS_BASE}/Database/ElastiCache.png`,
  'Redshift': `${AWS_BASE}/Analytics/Redshift.png`,
  'Aurora': `${AWS_BASE}/Database/Aurora.png`,
  'Aurora DB': `${AWS_BASE}/Database/Aurora.png`,
  
  'SQS': `${AWS_BASE}/ApplicationIntegration/SimpleQueueService.png`,
  'SQS Queue': `${AWS_BASE}/ApplicationIntegration/SimpleQueueService.png`,
  'SNS': `${AWS_BASE}/ApplicationIntegration/SimpleNotificationService.png`,
  'SNS Topic': `${AWS_BASE}/ApplicationIntegration/SimpleNotificationService.png`,
  'EventBridge': `${AWS_BASE}/ApplicationIntegration/EventBridge.png`,
  
  'IAM': `${AWS_BASE}/SecurityIdentityCompliance/IdentityandAccessManagement.png`,
  'IAM Policy': `${AWS_BASE}/SecurityIdentityCompliance/IdentityandAccessManagement.png`,
  'KMS': `${AWS_BASE}/SecurityIdentityCompliance/KeyManagementService.png`,
  'KMS Key': `${AWS_BASE}/SecurityIdentityCompliance/KeyManagementService.png`,
  
  'CloudWatch': `${AWS_BASE}/ManagementGovernance/CloudWatch.png`,
  'CloudFormation': `${AWS_BASE}/ManagementGovernance/CloudFormation.png`,
};

const SIMPLE_MAP: Record<string, string> = {
  // GCP
  'Compute Engine': `${SIMPLE_BASE}/googlecloud.svg`,
  'Cloud Run': `${SIMPLE_BASE}/googlecloud.svg`,
  'GKE': `${SIMPLE_BASE}/kubernetes.svg`,
  'GKE Cluster': `${SIMPLE_BASE}/kubernetes.svg`,
  'Cloud Storage': `${SIMPLE_BASE}/googlecloud.svg`,
  'Persistent Disk': `${SIMPLE_BASE}/googlecloud.svg`,
  'BigQuery': `${SIMPLE_BASE}/googlecloud.svg`,
  'Cloud SQL': `${SIMPLE_BASE}/googlecloud.svg`,
  'Cloud Spanner': `${SIMPLE_BASE}/googlecloud.svg`,
  'Firestore': `${SIMPLE_BASE}/firebase.svg`,
  'Pub/Sub': `${SIMPLE_BASE}/googlecloud.svg`,
  'Pub/Sub Broker': `${SIMPLE_BASE}/googlecloud.svg`,
  'Cloud IAM': `${SIMPLE_BASE}/googlecloud.svg`,
  // Azure
  'Azure VM': `${SIMPLE_BASE}/microsoftazure.svg`,
  'App Service': `${SIMPLE_BASE}/microsoftazure.svg`,
  'AKS': `${SIMPLE_BASE}/kubernetes.svg`,
  'AKS Cluster': `${SIMPLE_BASE}/kubernetes.svg`,
  'Blob Storage': `${SIMPLE_BASE}/microsoftazure.svg`,
  'Disk Storage': `${SIMPLE_BASE}/microsoftazure.svg`,
  'Azure SQL': `${SIMPLE_BASE}/microsoftazure.svg`,
  'Azure SQL DB': `${SIMPLE_BASE}/microsoftazure.svg`,
  'Cosmos DB': `${SIMPLE_BASE}/microsoftazure.svg`,
  'Service Bus': `${SIMPLE_BASE}/microsoftazure.svg`,
  'Azure AD': `${SIMPLE_BASE}/microsoftazure.svg`,
  'Entra ID (AD)': `${SIMPLE_BASE}/microsoftazure.svg`,
  // DevOps
  'Docker': `${SIMPLE_BASE}/docker.svg`,
  'Docker Container': `${SIMPLE_BASE}/docker.svg`,
  'Kubernetes': `${SIMPLE_BASE}/kubernetes.svg`,
  'Helm': `${SIMPLE_BASE}/helm.svg`,
  'Helm Chart': `${SIMPLE_BASE}/helm.svg`,
  'Terraform': `${SIMPLE_BASE}/terraform.svg`,
  'Terraform IaC': `${SIMPLE_BASE}/terraform.svg`,
  'Jenkins': `${SIMPLE_BASE}/jenkins.svg`,
  'Jenkins CI/CD': `${SIMPLE_BASE}/jenkins.svg`,
  'Prometheus': `${SIMPLE_BASE}/prometheus.svg`,
  'Grafana': `${SIMPLE_BASE}/grafana.svg`,
  'Grafana Board': `${SIMPLE_BASE}/grafana.svg`,
  'GitHub': `${SIMPLE_BASE}/github.svg`,
  'GitHub Repo': `${SIMPLE_BASE}/github.svg`,
  'GitLab': `${SIMPLE_BASE}/gitlab.svg`,
  'GitLab CI': `${SIMPLE_BASE}/gitlab.svg`,
  // Databases
  'PostgreSQL': `${SIMPLE_BASE}/postgresql.svg`,
  'MySQL': `${SIMPLE_BASE}/mysql.svg`,
  'MySQL Server': `${SIMPLE_BASE}/mysql.svg`,
  'SQLite': `${SIMPLE_BASE}/sqlite.svg`,
  'MongoDB': `${SIMPLE_BASE}/mongodb.svg`,
  'Redis': `${SIMPLE_BASE}/redis.svg`,
  'Redis Cache': `${SIMPLE_BASE}/redis.svg`,
  'Elasticsearch': `${SIMPLE_BASE}/elasticsearch.svg`,
  'Cassandra': `${SIMPLE_BASE}/apachecassandra.svg`,
  'Cassandra DB': `${SIMPLE_BASE}/apachecassandra.svg`,
  'Neo4j': `${SIMPLE_BASE}/neo4j.svg`,
  'Neo4j Graph': `${SIMPLE_BASE}/neo4j.svg`,
  // Languages
  'HTML5': `${SIMPLE_BASE}/html5.svg`,
  'HTML5 Page': `${SIMPLE_BASE}/html5.svg`,
  'CSS3': `${SIMPLE_BASE}/css3.svg`,
  'CSS3 Styles': `${SIMPLE_BASE}/css3.svg`,
  'JavaScript': `${SIMPLE_BASE}/javascript.svg`,
  'TypeScript': `${SIMPLE_BASE}/typescript.svg`,
  'React': `${SIMPLE_BASE}/react.svg`,
  'React.js': `${SIMPLE_BASE}/react.svg`,
  'NodeJS': `${SIMPLE_BASE}/nodedotjs.svg`,
  'Node.js Runtime': `${SIMPLE_BASE}/nodedotjs.svg`,
  'Python': `${SIMPLE_BASE}/python.svg`,
  'Python Script': `${SIMPLE_BASE}/python.svg`,
  'Golang': `${SIMPLE_BASE}/go.svg`,
  'Go Executable': `${SIMPLE_BASE}/go.svg`,
  'Rust': `${SIMPLE_BASE}/rust.svg`,
  'Rust Library': `${SIMPLE_BASE}/rust.svg`,
  'Java': `${SIMPLE_BASE}/oracle.svg`,
  'Java Application': `${SIMPLE_BASE}/oracle.svg`,
  // SaaS
  'Stripe': `${SIMPLE_BASE}/stripe.svg`,
  'Stripe Payment': `${SIMPLE_BASE}/stripe.svg`,
  'PayPal': `${SIMPLE_BASE}/paypal.svg`,
  'PayPal Gateway': `${SIMPLE_BASE}/paypal.svg`,
  'SendGrid': `${SIMPLE_BASE}/twilio.svg`,
  'SendGrid Mail': `${SIMPLE_BASE}/twilio.svg`,
  'Twilio': `${SIMPLE_BASE}/twilio.svg`,
  'Twilio API': `${SIMPLE_BASE}/twilio.svg`,
  'Auth0': `${SIMPLE_BASE}/auth0.svg`,
  'Auth0 Portal': `${SIMPLE_BASE}/auth0.svg`,
  'Slack': `${SIMPLE_BASE}/slack.svg`,
  'Slack Webhook': `${SIMPLE_BASE}/slack.svg`,
  'Discord': `${SIMPLE_BASE}/discord.svg`,
  'Discord Bot': `${SIMPLE_BASE}/discord.svg`,
  'Firebase': `${SIMPLE_BASE}/firebase.svg`,
  'Firebase DB': `${SIMPLE_BASE}/firebase.svg`,
  'Supabase': `${SIMPLE_BASE}/supabase.svg`,
  'Supabase Server': `${SIMPLE_BASE}/supabase.svg`,
};

export const getSymbolIconUrl = (type: string): string | null => {
  if (AWS_MAP[type]) return AWS_MAP[type];
  if (SIMPLE_MAP[type]) return SIMPLE_MAP[type];
  return null;
};
